name: Test Go App

# on:
#   push:
#     branches: [main]

on:
  workflow_dispatch

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test & Build Go App
      uses: ./.github/actions/build