name: Check Runner

# on:
#   workflow_dispatch

on:
  workflow_dispatch:
  schedule:
    # Runs every Sunday at 18:30
    - cron: '0 */8 * * *'


jobs:
  check-runner:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check self-hosted runner
        run: echo "Job to ensure runner gha-runner-opensourcegeeks-newsletter is still running!"
