name: Generate Contributors

# on:
#   push:
#     branches: [main]

on:
  workflow_dispatch

jobs:
  contributors-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Contribute List
        uses: BobAnkh/add-contributors@master
        with:
          CONTRIBUTOR: '## Contributors'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: ${{ github.token }}
          IMG_WIDTH: '50'
          FONT_SIZE: '14'
          PATH: '/README.md'
          COMMIT_MESSAGE: 'docs(README): update contributors'
          AVATAR_SHAPE: 'round'